const joker1 = {
  image: require('../assets/images/levels/joker-leve-1.png'),
  correct: true,
};

const joker2 = {
  image: require('../assets/images/levels/joker-level-3.png'),
  correct: true,
};

const joker3 = {
  image: require('../assets/images/levels/joker-level-6.png'),
  correct: true,
};

const joker4 = {
  image: require('../assets/images/levels/joker-level-9.png'),
  correct: true,
};

const joker5 = {
  image: require('../assets/images/levels/joker-level-12.png'),
  correct: true,
};

const policeman1 = {
  image: require('../assets/images/levels/policeman-1.png'),
  correct: false,
};
const policeman2 = {
  image: require('../assets/images/levels/policeman-2.png'),
  correct: false,
};
const batman1 = {
  image: require('../assets/images/levels/batman-1.png'),
  correct: false,
};
const batman2 = {
  image: require('../assets/images/levels/batman-2.png'),
  correct: false,
};
const batman3 = {
  image: require('../assets/images/levels/batman-3.png'),
  correct: false,
};
const batman4 = {
  image: require('../assets/images/levels/batman-4.png'),
  correct: false,
};
export const levels = [
  {
    id: 1,
    time: 5,
    allVariant: 9,
    wrongAttemptAmount: 1,
    images: [
      joker1,
      joker2,
      joker3,
      policeman1,
      policeman2,
      batman1,
      batman2,
      batman3,
      batman4,
    ],
    correctVariant: 3,
    column: 3,
    row: 3,
  },
  {
    id: 2,
    time: 5,
    allVariant: 12,
    wrongAttemptAmount: 1,
    column: 3,
    images: [
      joker1,
      joker2,
      joker3,
      joker4,
      policeman1,
      policeman2,
      batman1,
      batman2,
      batman3,
      batman3,
      batman4,
      policeman1,
    ],
    correctVariant: 4,
  },
  {
    id: 3,
    time: 4,
    allVariant: 12,
    wrongAttemptAmount: 1,
    column: 3,
    images: [
      joker1,
      joker2,
      joker3,
      joker3,
      joker4,
      policeman1,
      policeman2,
      batman1,
      batman2,
      batman3,
      batman3,
      batman4,
    ],
    correctVariant: 5,
  },
  {
    id: 4,
    time: 6,
    allVariant: 15,
    wrongAttemptAmount: 2,
    column: 3,
    images: [
      joker1,
      joker2,
      joker2,
      joker3,
      joker3,
      joker4,
      policeman1,
      policeman1,
      policeman2,
      policeman2,
      batman1,
      batman2,
      batman2,
      batman3,
      batman4,
    ],
    correctVariant: 6,
  },
  {
    id: 5,
    time: 5,
    allVariant: 15,
    wrongAttemptAmount: 2,
    column: 3,
    images: [
      joker1,
      joker2,
      joker2,
      joker3,
      joker3,
      joker4,
      policeman1,
      policeman1,
      policeman2,
      policeman2,
      batman1,
      batman2,
      batman2,
      batman3,
      batman4,
    ],
    correctVariant: 6,
  },
  {
    id: 6,
    time: 7,
    allVariant: 18,
    wrongAttemptAmount: 2,
    column: 3,
    images: [
      joker1,
      joker1,
      joker2,
      joker2,
      joker3,
      joker3,
      joker4,
      policeman1,
      policeman1,
      policeman1,
      policeman2,
      policeman2,
      batman1,
      batman2,
      batman2,
      batman3,
      batman4,
      batman4,
    ],
    correctVariant: 7,
  },
  {
    id: 7,
    time: 7,
    column: 4,
    wrongAttemptAmount: 3,
    images: [
      joker1,
      joker1,
      joker2,
      joker2,
      joker3,
      joker3,
      joker4,
      policeman1,
      policeman1,
      policeman1,
      policeman2,
      policeman2,
      batman1,
      batman1,
      batman2,
      batman2,
      batman3,
      batman3,
      batman4,
      batman4,
    ],
    allVariant: 20,
    correctVariant: 7,
  },
  {
    id: 8,
    time: 8,
    column: 4,
    wrongAttemptAmount: 3,
    images: [
      joker1,
      joker1,
      joker2,
      joker2,
      joker3,
      joker3,
      joker4,
      joker4,
      policeman1,
      policeman1,
      policeman2,
      policeman2,
      batman1,
      batman1,
      batman2,
      batman2,
      batman3,
      batman3,
      batman4,
      batman4,
    ],
    allVariant: 20,
    correctVariant: 8,
  },
  {
    id: 9,
    time: 8,
    wrongAttemptAmount: 3,
    column: 4,
    images: [
      joker1,
      joker1,
      joker2,
      joker2,
      joker3,
      joker3,
      joker4,
      joker4,
      policeman1,
      policeman1,
      policeman1,
      policeman2,
      policeman2,
      batman1,
      batman1,
      batman1,
      batman2,
      batman2,
      batman2,
      batman3,
      batman3,
      batman4,
      batman4,
      batman4,
    ],
    allVariant: 24,
    correctVariant: 8,
  },
  {
    id: 10,
    time: 9,
    column: 4,
    wrongAttemptAmount: 1,
    images: [
      joker1,
      joker1,
      joker2,
      joker2,
      joker3,
      joker3,
      joker4,
      joker4,
      joker4,
      policeman1,
      policeman1,
      policeman2,
      policeman2,
      batman1,
      batman1,
      batman1,
      batman2,
      batman2,
      batman2,
      batman3,
      batman3,
      batman4,
      batman4,
      batman4,
    ],
    allVariant: 24,
    correctVariant: 9,
  },
];
